name: Process Adblock Files

on:
  push:
    paths:
      - 'adblock_reject_egern.yaml'
      - 'adblock_reject_egern.txt'
  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process files
        run: |
          import re
          from datetime import datetime
          import os

          def process_file(input_file, output_file):
              if not os.path.exists(input_file):
                  print(f"Error: Input file {input_file} does not exist.")
                  return False

              # ... [之前的处理逻辑保持不变] ...

              return True

          # 处理文件并检查结果
          yaml_success = process_file('adblock_reject_egern.yaml', 'adblock_reject_egern_module.yaml')
          txt_success = process_file('adblock_reject_egern.txt', 'adblock_reject_egern_module.txt')

          if not (yaml_success and txt_success):
              raise Exception("File processing failed")

        shell: python

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add adblock_reject_egern_module.yaml adblock_reject_egern_module.txt
          git status
          git commit -m "Process adblock files" || echo "No changes to commit"
          git push || (echo "Push failed" && git push --force)
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Check for errors
        if: failure()
        run: |
          echo "Workflow failed. Here's some debug information:"
          git status
          git remote -v
